DateTime=2023-03-01 19:39:31,909 loglevel=WARNING  log_response() L241  Not Found: /api/detail/22/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-01 19:39:31,909 loglevel=WARNING  log_message() L187  "GET //api/detail/22/ HTTP/1.1" 404 14 call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/core/servers/basehttp.py L187 
DateTime=2023-03-01 19:39:32,293 loglevel=ERROR   log_response() L241  Internal Server Error: /api/put/22/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
Traceback (most recent call last):
  File "/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/gustavo/myManageLogs/backend/mymanagelogs/views.py", line 49, in modifiedLogs
    log = Logs.objects.get(id=pk)
  File "/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
mymanagelogs.models.Logs.DoesNotExist: Logs matching query does not exist.
DateTime=2023-03-01 19:39:32,294 loglevel=ERROR   log_message() L187  "PUT //api/put/22/ HTTP/1.1" 500 111322 call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/core/servers/basehttp.py L187 
DateTime=2023-03-02 09:56:07,758 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 09:56:30,137 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 09:58:42,038 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 09:59:30,070 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:00:01,700 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:00:25,854 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:01:56,140 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:02:36,147 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:25:16,039 loglevel=WARNING  log_response() L241  Not Found: /apidetail/1/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:29:29,378 loglevel=WARNING  log_response() L241  Not Found: /api/detail/1/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:29:53,136 loglevel=WARNING  log_response() L241  Not Found: /api/detail/1/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:31:54,639 loglevel=WARNING  log_response() L241  Not Found: /api/detail/1/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:35:22,103 loglevel=WARNING  log_response() L241  Not Found: /api/detail/1/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:36:31,936 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:36:31,939 loglevel=WARNING  log_response() L241  Not Found: /api/detail/1/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:50:19,389 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:50:19,393 loglevel=WARNING  log_response() L241  Not Found: /api/detail/1/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:51:51,050 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:51:51,053 loglevel=WARNING  log_response() L241  Not Found: /api/detail/1/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:53:34,557 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:53:34,561 loglevel=WARNING  log_response() L241  Not Found: /api/detail/1/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:54:07,380 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:54:07,385 loglevel=WARNING  log_response() L241  Not Found: /api/detail/1/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:54:20,944 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:54:20,948 loglevel=WARNING  log_response() L241  Not Found: /api/detail/1/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:55:16,653 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 10:55:16,658 loglevel=WARNING  log_response() L241  Not Found: /api/detail/1/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:13:14,499 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:14:01,103 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:15:13,160 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:16:21,936 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:17:04,667 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:17:19,896 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:19:08,957 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:28:57,500 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:30:23,366 loglevel=WARNING  log_response() L241  Bad Request: /api/post/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:35:57,352 loglevel=WARNING  log_response() L241  Bad Request: /api/put/4/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:36:58,530 loglevel=WARNING  log_response() L241  Bad Request: /api/put/4/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:37:14,073 loglevel=WARNING  log_response() L241  Bad Request: /api/put/4/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:41:26,967 loglevel=WARNING  log_response() L241  Not Found: /('api/put/4/', {'message': 'update message'}) call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:42:00,842 loglevel=WARNING  log_response() L241  Bad Request: /api/put/4/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:42:22,253 loglevel=WARNING  log_response() L241  Bad Request: /api/put/4/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:43:00,468 loglevel=WARNING  log_response() L241  Not Found: /('api/put/4/', {'message': 'update message'}) call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:43:12,541 loglevel=WARNING  log_response() L241  Not Found: /('api/put/4/', {'message': 'update message'}) call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:49:28,718 loglevel=WARNING  log_response() L241  Not Found: /api/delete/1/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
DateTime=2023-03-02 11:49:28,723 loglevel=WARNING  log_response() L241  Not Found: /api/detail/1/ call_trace=/home/gustavo/.local/share/virtualenvs/myManageLogs-WzAjrBSH/lib/python3.10/site-packages/django/utils/log.py L241 
